name = "LikelihoodProfiler"
uuid = "93acb638-a083-5915-8dce-d129bc6a3f59"
keywords = ["package", "identifiability", "modeling"]
license = "MIT"
desc = "practical identifiability analysis and confidence intervals evaluation"
authors = ["borisov <iv.borissov@gmail.com>", "metelkin <evgeny.metelkin@gmail.com>"]
repo-url = "https://github.com/insysbio/LikelihoodProfiler.jl"
version = "0.5.0"

[deps]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
Calculus = "0.5.1"
ForwardDiff = "0.10"
NLopt = "0.6, 1.0.0 - 1.0.1"
PlotUtils = "1.4"
ProgressMeter = "1.10"
RecipesBase = "1.1"
julia = "1.7"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots"]
