name = "LikelihoodProfiler"
uuid = "934dfcd9-de73-50b3-9b48-36c923fd8802"
keywords = ["package", "management"]
license = "MIT"
desc = "The next-generation Julia package manager."
authors = ["borisov <iv.borissov@gmail.com>", "metelkin <evgeny.metelkin@gmail.com>"]
repo-url = "https://github.com/insysbio/LikelihoodProfiler.jl"
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = ">=0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
