[deps]
CICOBase = "33444335-3134-4342-4659-594331344435"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
OptimizationLBFGSB = "22f7324a-a79d-40f2-bebe-3af60c77bd15"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
CICOBase = "0.6.0"
Documenter = "1"
OrdinaryDiffEq = "6"
